name: Windows Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg dependencies
        run: vcpkg install --triplet x64-windows

      - name: Configure CMake
        # Methana $env:VCPKG_INSTALLATION_ROOT kiyana eka PowerShell waladi hariyata wada karanawa
        run: |
          cmake -B build -S . "-DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build Project
        run: cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DanithuClipboardManager
          path: build/Release/*.exe