name: Windows Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg dependencies
        run: vcpkg install --triplet x64-windows

      - name: Configure CMake
        run: cmake -B build -S . "-DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build Project
        run: cmake --build build --config Release

      - name: Prepare Release
        run: |
          mkdir dist
          copy build\Release\*.exe dist\
          copy vcpkg_installed\x64-windows\bin\*.dll dist\

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DanithuClipboard_Pro
          path: dist/